In [15]:
import numpy as np

### Creating 1-D array

In [16]:
ar=np.array([1,4,6,3,7])
ar

array([1, 4, 6, 3, 7])

In [17]:
ar1=np.array((2,3,4,5))
ar1

array([2, 3, 4, 5])

### Creating 2-D array

In [18]:
arr=np.array([[1,2,4], [5,6,8]])
arr

array([[1, 2, 4],
       [5, 6, 8]])

### Creating 3-D array

In [19]:
arr=np.array([[[1,2,3], [5,6,7]], [[1,2,3], [5,6,7]]])
arr

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

### Accessing elements

In [20]:
ar=np.array([1,4,6,3,7])
ar[2]

6

In [21]:
arr=np.array([[1,2,4], [5,6,8]])
arr[0,1]

2