In [1]:
import numpy as np

### ones() function

In [2]:
arr=np.ones(2)
arr

array([1., 1.])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### zeros() function

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

### eye() function

In [6]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

### around() function

In [ ]:
arr=np.array([1.432, 3.087, 4.56])
np.around(arr)

In [ ]:
np.around(arr,2)

### linspace() function

In [ ]:
np.linspace(0,10,5)